<a href="https://colab.research.google.com/github/sandeepshabd/DeepLearning_Masters/blob/main/week1/DeepLearning_weekl1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
a= torch.arange(10)
b= torch.arange(10)*10
print(a)
print(b)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [4]:
a+b

tensor([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [5]:
a.shape, b.shape

(torch.Size([10]), torch.Size([10]))

In [7]:
a[None,:,None].shape

torch.Size([1, 10, 1])

In [12]:
a[None,:,None]

tensor([[[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]])

In [17]:
c=a[None,:]
c.shape

torch.Size([1, 10])

In [18]:
c[:,0].shape

torch.Size([1])

In [19]:
(a[None,:]+b[None,:])

tensor([[ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99]])

In [20]:
torch.ones(3,2)+10

tensor([[11., 11.],
        [11., 11.],
        [11., 11.]])

In [21]:
torch.ones(3,2)+torch.ones(2,3)

RuntimeError: ignored

In [22]:
torch.ones(3,1)+torch.ones(1,3) #broadcasting

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [23]:
a[None,:]+b[:,None] #broadcasting allows to match other tensors

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
a[None,:].repeat(10,1)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [30]:
b[:,None].repeat(1,10)


tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
        [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
        [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
        [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
        [60, 60, 60, 60, 60, 60, 60, 60, 60, 60],
        [70, 70, 70, 70, 70, 70, 70, 70, 70, 70],
        [80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
        [90, 90, 90, 90, 90, 90, 90, 90, 90, 90]])

In [31]:
a[None,:].repeat(10,1) + b[:,None].repeat(1,10)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
b[:,None].repeat(1,10) - a[None,:].repeat(10,1)

tensor([[ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9],
        [10,  9,  8,  7,  6,  5,  4,  3,  2,  1],
        [20, 19, 18, 17, 16, 15, 14, 13, 12, 11],
        [30, 29, 28, 27, 26, 25, 24, 23, 22, 21],
        [40, 39, 38, 37, 36, 35, 34, 33, 32, 31],
        [50, 49, 48, 47, 46, 45, 44, 43, 42, 41],
        [60, 59, 58, 57, 56, 55, 54, 53, 52, 51],
        [70, 69, 68, 67, 66, 65, 64, 63, 62, 61],
        [80, 79, 78, 77, 76, 75, 74, 73, 72, 71],
        [90, 89, 88, 87, 86, 85, 84, 83, 82, 81]])

In [35]:
(torch.ones(100)+torch.ones(100)).shape

torch.Size([100])

In [38]:
(torch.ones(100,1)+torch.ones(100,1)).shape

torch.Size([100, 1])

In [39]:
(torch.ones(100,1)+torch.ones(1,100)).shape

torch.Size([100, 100])

In [40]:
(torch.ones(2,3)+1).shape

torch.Size([2, 3])

In [41]:
(torch.ones(2,3)*0).shape

torch.Size([2, 3])

In [42]:
(torch.ones(1,5)+torch.ones(5,1)).shape

torch.Size([5, 5])

In [43]:
(torch.ones(2,5)+torch.ones(5,2)).shape

RuntimeError: ignored

In [44]:
(torch.ones(1,1,5)+torch.ones(5,1,1)).shape

torch.Size([5, 1, 5])